### PR TITLE
Info Module part 2 -- Goal Section

### PR DESCRIPTION
**Pull request by YLee2121**
# Info Module -- Goal Section (Based on #22)

## 📃Summary

The goal section aims to track the short-term goal for the specific exercise to improve the training weight. The user can pick an untracked exercise and pick a desired progress, then it will be presented as the progress bar with a pulsing animation 🎆🎇. Each progress bar has the `Update` and `Delete` methods. 

### MainInfoView

* Several mock `Model` and `ViewModel` support all the functionality. Go to `Files changed` for more details.

* Construct the goal section with the title and a list of progress bars. 

### MainInfoView_GoalSheet

* The sheet for `add` and `update` the progress bar (goal).

* 🛑 To avoid the duplication of codes, two methods are embedded in the same `View` with the control unit to decide the presenting layout and corresponding functionality. However, the two methods are basically equivalent and similar in the UI perspective. If separating the view is better, I am open to implement it.

### MainInfoView_GoalListRow

* Each goal row consists of a `progressBar`, a `updateButton`, and a `deleteButton`

### PulseProgressBar

* A progress which can show the progress percentage. It has a set of animation control units, `pulseEffect` and `pulseAnimationIsActive`.

* `pulseEffect` is the animation itself, it could transfer between `true` and `false` to achieve the animation.

* `pulseAnimationIsActive` aims to control the overall animation on `pulseEffect` between animation and no animation. Due to the `repeatForever` on `pulseEffect`, every time the new goal is created, the old `progressBar` would add on a new animation; therefore, it causes the different pulsing numbers within the bar. `pulseAnimationIsActive` aims to ease this issue, it would reset the overall animation and restart again to guarantee the pulsing amount.

## 📷Screenshots

* Add New Goal

imageimageimage

* Update & Delete

imageimage

### CODE REVIEW

**Comment by alex308248** [comment]
Looks really good to me. But I'm wondering that what's the goal means. Does that mean the weight of an exercise that customer can lift? If yes, than we will need to extract data in the future.

**Comment by YLee2121** [comment]
> Looks really good to me. But I'm wondering that what's the goal means. Does that mean the weight of an exercise that customer can lift? If yes, than we will need to extract data in the future.


So a goal is the training weight that the user wants to achieve. 
For example, I can do 500 lb for 1 PR right now, and I wish I can do 520 lb in the future as my goal. Therefore, I set a goal of 520 lb, and what I am working on is improving from 500 lb to 520 lb.
This is a goal! And for me, it's exciting to see my progress increasing little by little, that's why I design the Goal Bar.

**Comment by alex308248** [comment]
> > Looks really good to me. But I'm wondering that what's the goal means. Does that mean the weight of an exercise that customer can lift? If yes, than we will need to extract data in the future.
> 
> So a goal is the training weight that the user wants to achieve. For example, I can do 500 lb for 1 PR right now, and I wish I can do 520 lb in the future as my goal. Therefore, I set a goal of 520 lb, and what I am working on is improving from 500 lb to 520 lb. This is a goal! And for me, it's exciting to see my progress increasing little by little, that's why I design the Goal Bar.

Got it, that make sense. But does that mean we will need to set up our start weight and goal weight everytime we create a new goal? Cause I can only find a picker for new progress.

**Comment by YLee2121** [comment]
> > > Looks really good to me. But I'm wondering that what's the goal means. Does that mean the weight of an exercise that customer can lift? If yes, than we will need to extract data in the future.
> > 
> > 
> > So a goal is the training weight that the user wants to achieve. For example, I can do 500 lb for 1 PR right now, and I wish I can do 520 lb in the future as my goal. Therefore, I set a goal of 520 lb, and what I am working on is improving from 500 lb to 520 lb. This is a goal! And for me, it's exciting to see my progress increasing little by little, that's why I design the Goal Bar.
> 
> Got it, that make sense. But does that mean we will need to set up our start weight and goal weight everytime we create a new goal? Cause I can only find a picker for new progress.

No, we don't need to set up the start weight. The start weight will be determined by the heaviest weight of a specific exercise throughout the training history. All you need to do is pick an exercise and pick progress for adding a new goal.

**Comment by alex308248** [comment]
> > > > Looks really good to me. But I'm wondering that what's the goal means. Does that mean the weight of an exercise that customer can lift? If yes, than we will need to extract data in the future.
> > > 
> > > 
> > > So a goal is the training weight that the user wants to achieve. For example, I can do 500 lb for 1 PR right now, and I wish I can do 520 lb in the future as my goal. Therefore, I set a goal of 520 lb, and what I am working on is improving from 500 lb to 520 lb. This is a goal! And for me, it's exciting to see my progress increasing little by little, that's why I design the Goal Bar.
> > 
> > 
> > Got it, that make sense. But does that mean we will need to set up our start weight and goal weight everytime we create a new goal? Cause I can only find a picker for new progress.
> 
> No, we don't need to set up the start weight. The start weight will be determined by the heaviest weight of a specific exercise throughout the training history. All you need to do is pick an exercise and pick progress for adding a new goal.

Got it!

**Pull request merged**
