### PR TITLE
Upgrade IntroHistoryView

### PR DESCRIPTION
**Pull request by YLee2121**
# Upgrade IntroHistoryView

## 🍕 Change Icon

* Swipe right icon, edit icon (open to discussion)

## 🔴 Add an Alert  

* When the user clicks the delete button, the alert will appear as a confirmation dialog.

## 📸 Screenshots

* Icon Change

image

* Alert

image

### CODE REVIEW

**Comment by cheniwei** [comment]
I'm curious about what's the meaning of changing icon 🤔?

**Comment by YLee2121** [comment]
> I'm curious about what's the meaning of changing icon 🤔?

@alex308248 says the old one was not straightforward enough, so I PR a new idea for the new feedback

**Review by alex308248 — APPROVED** [review]
Looks much better!!

**Review by cheniwei — APPROVED** [review]
Approved.

**Pull request merged**
